authors/urls.py
from django.urls import path

from authors import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path(
        'dashboard/recipe/create/',
        views.DashboardRecipes.as_view(),
        name='dashboard_recipe_create',
    ),
    path(
        'dashboard/recipe/delete/',
        views.DashboardRecipesDelete.as_view(),
        name='dashboard_recipe_delete',
    ),
    path(
        'dashboard/recipe/<int:id>/edit/',
        views.DashboardRecipes.as_view(),
        name='dashboard_recipe_edit',
    ),
]

projeto_django_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('recipes/search/', views.SearchListView.as_view(), name='search'),
    path(
        'recipes/category/<int:category_id>/',
        views.CategoryListView.as_view(),
        name='category',
    ),
    path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name='recipe'),
]

templates/global/partials/footer.html
<footer class="main-footer">
  <div class="developer">
    <a href="https://www.rajr.informatica.com" target="_blank" rel="noreferrer nooperner">By JRF</a>
  </div>

  <div class="powered">
    <a href="https://www.djangoproject.com" target="_blank" rel="noreferrer nooperner">Powered by Django</a>
  </div>
</footer>

templates/global/partials/form.html
<div class="main-content container">
  <form class="main-form" method="POST" action="{{ form_action }}" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-content form-content-grid">
      {% for field in form %}
        <div class="form-group {{ field.field.widget.attrs.class }}">
          <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}

          {% if field.help_text %}
            <p class="help-text">{{ field.help_text }}</p>
          {% endif %}

          {{ field.errors }}
        </div>
        
        {% if field.name == 'cover' and field.value.url %}
          <div class="span-2">
            <img src="{{ field.value.url }}" alt="{{ recipe.title }}">
          </div>
        {% endif %}
      {% endfor %}
    </div>

    <!-- div class="form-content form-content-grid">
      <div class="form-group">
        {{ form.errors }}
      </div>
    </div -->

    <div class="form-content form-content-grid">
      <div class="form-group">
        <button type="submit">Registar</button>
      </div>
    </div>
  </form>
</div>

templates/global/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css"
  integrity="sha512-B46MVOJpI6RBsdcU307elYeStF2JKT87SsHZfRSkjVi4/iZ3912zXi45X5/CBr/GbCyLx6M1GQtTKYRd52Jxgw=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/brands.min.css"
  integrity="sha512-EJp8vMVhYl7tBFE2rgNGb//drnr1+6XKMvTyamMS34YwOEFohhWkGq13tPWnK0FbjSS6D8YoA3n3bZmb3KiUYA=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/solid.min.css"
  integrity="sha512-/r+0SvLvMMSIf41xiuy19aNkXxI+3zb/BN8K9lnDDWI09VM0dwgTMzK7Qi5vv5macJ3VH4XZXr60ip7v13QnmQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'global/css/styles.css' %}">

templates/global/partials/header.html
<header class="main-header-container">
  <div class="main-header container">
    <h1>
      <a class="main-logo" href="{% url "recipes:home" %}">
        <i class="fas fa-utensils main-logo-icon"></i>
        <span class="main-logo-text">Receitas</span>
      </a>
    </h1>
  </div>
</header>

templates/global/partials/messages.html
{% if messages %}
  <div class="main-content center container messages-container">
    {% for message in messages %}
      <div class="message {{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  </div>
{% endif %}

templates/global/partials/pagination.html
{% if recipes.has_other_pages %}
  <nav role="navigation" aria-label="Pagination" class="container pagination">
    <div class="pagination-content">
      {% if pagination_range.has_previous %}
        <a class="page-link page-item" aria-label="Go to page 1" href="?page=1{{ url_query }}">1</a>
        <span class="page-item">...</span>
      {% endif %}

      {% for page in pagination_range.pagination %}
        {% if page == pagination_range.current_page %}
          <a class="page-link page-item page-current" aria-label="Current page {{ page }}" 
            href="?page={{ page }}{{ url_query }}">{{ page }}</a>
        {% else %}
          <a class="page-link page-item" aria-label="Go to page {{ page }}" aria-current="true" 
           href="?page={{ page }}{{ url_query }}">
            {{ page }}
          </a>
        {% endif %}
      {% endfor %}

      {% if pagination_range.has_next %}
        <span class="page-item">...</span>
        <a class="page-link page-item" aria-label="Go to page {{ pagination_range.total_pages }}" 
         href="?page={{ pagination_range.total_pages }}{{ url_query }}">
          {{ pagination_range.total_pages }}
        </a>
      {% endif %}
    </div>
  </nav>
{% endif %}