authors/urls.py
from django.urls import path

from authors import views

app_name = 'authors'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path(
        'dashboard/recipe/create/',
        views.DashboardRecipes.as_view(),
        name='dashboard_recipe_create',
    ),
    path(
        'dashboard/recipe/delete/',
        views.DashboardRecipesDelete.as_view(),
        name='dashboard_recipe_delete',
    ),
    path(
        'dashboard/recipe/<int:id>/edit/',
        views.DashboardRecipes.as_view(),
        name='dashboard_recipe_edit',
    ),
]

projeto_django_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path

from recipes import views

app_name = 'recipes'

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('recipes/search/', views.SearchListView.as_view(), name='search'),
    path(
        'recipes/category/<int:category_id>/',
        views.CategoryListView.as_view(),
        name='category',
    ),
    path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name='recipe'),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=35)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=35)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=35)
    preparation_steps = models.TextField(max_length=255)
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', blank=True, default=''
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        default=None,
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipes:recipe', args=(self.id,))

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.title)}'
            self.slug = slug

        return super().save(*args, **kwargs)

authors/forms/recipe.py
from collections import defaultdict

from django import forms
from django.core.exceptions import ValidationError

from recipes.models import Recipe
from resources.utils.django_forms import add_attribute
from resources.utils.strings import is_positive_number


class AuthorsRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._my_errors = defaultdict(list)

        add_attribute(self.fields.get('preparation_steps'), 'class', 'span-2')

    class Meta:
        model = Recipe
        fields = [
            'title',
            'description',
            'preparation_time',
            'preparation_time_unit',
            'servings',
            'servings_unit',
            'preparation_steps',
            'cover',
        ]
        widgets = {
            'cover': forms.FileInput(attrs={'class': 'span-2'}),
            'servings_unit': forms.Select(
                choices=(
                    ('Porções', 'Porções'),
                    ('Unidade', 'Unidade'),
                    ('Pedaço', 'Pedaço'),
                    ('Litros', 'Litros'),
                    ('Fatias', 'Fatias'),
                    ('Pessoas', 'Pessoas'),
                )
            ),
            'preparation_time_unit': forms.Select(
                choices=(
                    ('Minutos', 'Minutos'),
                    ('Horas', 'Horas'),
                )
            ),
        }

    def clean_description(self):
        description = self.cleaned_data.get('description')

        if description is None or len(description) < 20:  # noqa: PLR2004
            self._my_errors['description'].append(
                'Descrição precisa ter no mínimo 20 caracteres',
            )

        return description

    def clean_preparation_time(self):
        preparation_time = self.cleaned_data.get('preparation_time')

        if not is_positive_number(preparation_time):
            self._my_errors['preparation_time'].append(
                'Tempo de preparo precisa ser positivo',
            )

        return preparation_time

    def clean_servings(self):
        servings = self.cleaned_data.get('servings')

        if not is_positive_number(servings):
            self._my_errors['servings'].append(
                'Quantidade de porções precisa ser positivo',
            )

        return servings

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)

        clean_data = self.cleaned_data

        title = clean_data.get('title')

        if title is None or len(title) < 5:  # noqa: PLR2004
            self._my_errors['title'].append(
                'Título precisa ter no mínimo 5 caracteres',
            )

        if self._my_errors:
            raise ValidationError(self._my_errors)

        return super_clean

recipes/views.py
import os

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render

from recipes.models import Recipe
from resources.utils.pagination import pagination

PER_PAGE = int(os.getenv('PER_PAGE', 6))  # noqa: PLW1508


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = pagination(request, recipes, PER_PAGE)

    return render(
        request,
        'recipes/pages/home.html',
        context={'recipes': page_obj, 'pagination_range': pagination_range},
    )


def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)

    return render(
        request,
        'recipes/pages/recipe-view.html',
        context={'recipe': recipe, 'is_detail_page': True},
    )


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id, is_published=True
        ).order_by('-id')
    )

    page_obj, pagination_range = pagination(request, recipes, PER_PAGE)

    return render(
        request,
        'recipes/pages/category.html',
        context={
            'recipes': page_obj,
            'pagination_range': pagination_range,
            'title': f'Categoria - {recipes[0].category.name} |',
        },
    )


def search(request):
    search_term = request.GET.get('search', '').strip()

    if not search_term:
        raise Http404

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term)
            | Q(description__icontains=search_term)
        ),
        is_published=True,
    ).order_by('-id')

    page_obj, pagination_range = pagination(request, recipes, PER_PAGE)

    return render(
        request,
        'recipes/pages/search.html',
        {
            'page_title': f'Search for "{search_term}" |',
            'search_term': search_term,
            'recipes': page_obj,
            'pagination_range': pagination_range,
            'url_query': f'&search={search_term}',
        },
    )

recipes/views/all_views.py
import os

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render

from recipes.models import Recipe
from resources.utils.pagination import pagination

PER_PAGE = int(os.getenv('PER_PAGE', 6))  # noqa: PLW1508


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = pagination(request, recipes, PER_PAGE)

    return render(
        request,
        'recipes/pages/home.html',
        context={'recipes': page_obj, 'pagination_range': pagination_range},
    )


def recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id, is_published=True)

    return render(
        request,
        'recipes/pages/recipe-view.html',
        context={'recipe': recipe, 'is_detail_page': True},
    )


def category(request, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id, is_published=True
        ).order_by('-id')
    )

    page_obj, pagination_range = pagination(request, recipes, PER_PAGE)

    return render(
        request,
        'recipes/pages/category.html',
        context={
            'recipes': page_obj,
            'pagination_range': pagination_range,
            'title': f'Categoria - {recipes[0].category.name} |',
        },
    )


def search(request):
    search_term = request.GET.get('search', '').strip()

    if not search_term:
        raise Http404

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term)
            | Q(description__icontains=search_term)
        ),
        is_published=True,
    ).order_by('-id')

    page_obj, pagination_range = pagination(request, recipes, PER_PAGE)

    return render(
        request,
        'recipes/pages/search.html',
        {
            'page_title': f'Search for "{search_term}" |',
            'search_term': search_term,
            'recipes': page_obj,
            'pagination_range': pagination_range,
            'url_query': f'&search={search_term}',
        },
    )

recipes/views/base.py
import os

from django.views.generic import ListView

from recipes.models import Recipe
from resources.utils.pagination import pagination

PER_PAGE = int(os.getenv('PER_PAGE', 6))  # noqa: PLW1508


class RecipeBaseListView(ListView):
    model = Recipe
    context_object_name = 'recipes'
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        page_obj, pagination_range = pagination(
            self.request, context.get('recipes'), PER_PAGE
        )

        context.update({
            'recipes': page_obj,
            'pagination_range': pagination_range,
        })

        return context

recipes/views/category.py
from django.http import Http404

from recipes.views.base import RecipeBaseListView


class CategoryListView(RecipeBaseListView):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(
            category__id=self.kwargs.get('category_id'), is_published=True
        )

        if not queryset:
            raise Http404

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'title': f'Categoria - {context.get("recipes")[0].category.name} |'
        })

        return context

recipes/views/detail.py
from django.views.generic import DetailView

from recipes.models import Recipe


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({'is_detail_page': True})

        return context

recipes/views/home.py
from recipes.views.base import RecipeBaseListView


class HomeListView(RecipeBaseListView):
    template_name = 'recipes/pages/home.html'

recipes/views/search.py
from django.db.models import Q
from django.http import Http404

from recipes.views.base import RecipeBaseListView


class SearchListView(RecipeBaseListView):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('search', '').strip()

        if not search_term:
            raise Http404

        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(
            Q(
                Q(title__icontains=search_term)
                | Q(description__icontains=search_term)
            ),
            is_published=True,
        )

        return queryset

    def get_context_data(self, *args, **kwargs):
        search_term = self.request.GET.get('search', '').strip()
        context = super().get_context_data(*args, **kwargs)

        context.update({
            'page_title': f'Search for "{search_term}" |',
            'search_term': search_term,
            'url_query': f'&search={search_term}',
        })

        return context

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css"
  integrity="sha512-B46MVOJpI6RBsdcU307elYeStF2JKT87SsHZfRSkjVi4/iZ3912zXi45X5/CBr/GbCyLx6M1GQtTKYRd52Jxgw=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/brands.min.css"
  integrity="sha512-EJp8vMVhYl7tBFE2rgNGb//drnr1+6XKMvTyamMS34YwOEFohhWkGq13tPWnK0FbjSS6D8YoA3n3bZmb3KiUYA=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/solid.min.css"
  integrity="sha512-/r+0SvLvMMSIf41xiuy19aNkXxI+3zb/BN8K9lnDDWI09VM0dwgTMzK7Qi5vv5macJ3VH4XZXr60ip7v13QnmQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/pagination.html
{% if recipes.has_other_pages %}
  <nav role="navigation" aria-label="Pagination" class="container pagination">
    <div class="pagination-content">
      {% if pagination_range.has_previous %}
        <a class="page-link page-item" href="?page=1{{ url_query }}">1</a>
        <span class="page-item">...</span>
      {% endif %}

      {% for page in pagination_range.pagination %}
        {% if page == pagination_range.current_page %}
          <a class="page-link page-item page-current" href="?page={{ page }}{{ url_query }}">{{ page }}</a>
        {% else %}
          <a class="page-link page-item" href="?page={{ page }}{{ url_query }}">{{ page }}</a>
        {% endif %}
      {% endfor %}

      {% if pagination_range.has_next %}
        <span class="page-item">...</span>
        <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}{{ url_query }}">{{ pagination_range.total_pages }}</a>
      {% endif %}
    </div>
  </nav>
{% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
  {% if recipe.cover %}
    <div class="recipe-cover">
      <a href={{ recipe.get_absolute_url }}>
        <img src={{ recipe.cover.url }} alt="Recipe Cover Image">
      </a>
    </div>
  {% endif %}
  <div class="recipe-title-container">
    <h2 class="recipe-title">
      <a href={{ recipe.get_absolute_url }}>
        {{ recipe.title }}
      </a>
    </h2>
  </div>

  <div class="recipe-author">
    <span class="recipe-author-item">
      <i class="fas fa-user"></i>
      {% if recipe.author.first_name %}
        {{ recipe.author.first_name }} {{ recipe.author.last_name }}
      {% else %}
        {{ recipe.author.username }}
      {% endif %}
    </span>
    <span class="recipe-author-item">
      <i class="fas fa-calendar-alt"></i>
      {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
    </span>

    {% if recipe.category is not None %}
    <span class="recipe-author-item">
      <a href={% url "recipes:category" recipe.category.id %}>
        <i class="fas fa-layer-group"></i>
        <span>{{ recipe.category.name }}</span>
      </a>
    </span>
    {% endif %}
  </div>

  <div class="recipe-content">
    <p>{{ recipe.description }}</p>
  </div>

  <div class="recipe-meta-container">
    <div class="recipe-meta recipe-preparation">
      <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
      <div class="recipe-meta-text">
        {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
      </div>
    </div>
    <div class="recipe-meta recipe-servings">
      <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
      <div class="recipe-meta-text">
        {{ recipe.servings }} {{ recipe.servings_unit }}
      </div>
    </div>
  </div>

  {% if is_detail_page is not True %}
    <footer class="recipe-footer">
      <a class="recipe-read-more button button-dark button-full-width" href="{{ recipe.get_absolute_url }}">
        <i class="fas fa-eye"></i>
        <span>ver mais...</span>
      </a>
    </footer>
  {% endif %}

  {% if is_detail_page is True %}
    <div class="preparation-steps">
      {% if recipe.preparation_steps_is_html is True %}
        {{ recipe.preparation_steps|safe }}
      {% else %}
        {{ recipe.preparation_steps|linebreaksbr }}
      {% endif %}
    </div>
  {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
  <div class="container">
    <form action="{% url 'recipes:search' %}" class="search-form" method="GET">
      <input type="search" class="search-input" name="search" placeholder="Search for recipes..." 
       value="{{ search_term }}" required>
      <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
    </form>
  </div>
</div>